### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by alex-angelov** [FrazLaw/RoboPot#20]
1) The web layout looks ok, but I wasn't able to find scripts for sensor data acquisition (which will save it to a file, then read by the php script);
2) Motor control functions need to be completed, probably after the circuit is built and tested. So far the functions are only listed;
3) There is no list of motor components, or a sketch/CAD of the motor car design. Will it be an off-the-shelf solution or would you build one?
4) More information about file formats, expected latency between system components, bit rate, needed;
5) Power considerations - will the Pi (assuming you won't use a PSU) be able to supply enough power for the sensors;
6) CPU benchmarks running parts of the project.
Very good github file management and history of commits.
- Team 11

**Comment by FMenziesENG** [comment]
Motor functions written. 
Robot Chassis and motors image and purchasing link added.
Latency information added to readme.
Power information added to readme.
