### ISSUE TITLE
I2C WORK TOGETHER

### ISSUE THREAD

**Issue by Kenny840394191** [FrazLaw/RoboPot#23]
How can you make two I2C devices work together? Raspberry pi3 have one I2C pin, how can you make two I2C devices work together,?

Team 15

**Comment by Fraser-Menzies-Engineer** [comment]
Each slave device on the bus has its own address. A slave device only performs an action if you specify its corresponding address.

"A particular strength of I²C is the capability of a microcontroller to control a network of device chips with just two general-purpose I/O pins and software."

https://en.wikipedia.org/wiki/I%C2%B2C
